apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  ports:
  - name: nginx-port
    port: 8080
    targetPort: 80
    nodePort: 30001
  selector:
    apps: nginx
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        apps: nginx
    spec:
      containers:
      - name: nginx-pod-ctn
        image: nginx:latest
        ports:
        - containerPort: 80
